spring:
  application:
    name: meli-orders

# Default active profile
spring:
  profiles:
    active: dev

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /swagger-config.yaml
